// skeleton-react-app/src/pages/Login/index.js
import React from 'react'
import './style.scss'
import { Link } from 'react-router-dom'
import capaImg from '../../assets/capa.png'


export default class Dashboard extends React.Component{
     render(){
        return(
                <div className="container-sides mt-10">

                <div className="container-left ac mt-9">
                    <img className="display-b ac" src={capaImg} alt="delivery"/>
                </div>

                <div className="container-rigth ac">
                    <div className="card card-login">


                            <h1 className="title txt-alg-c mt-3">Entrar</h1>

                            <form className="mt-5">
                                <input type="email" className="input-1 mt-2 ac" placeholder="email"/>
                                <input type="password" className="input-1 mt-4 ac" placeholder="senha"/>
                            </form>

                            
                            <div className="container-link-login ac mt-5">
                            <Link className="link-1" to="/Dashboard">
                                <button className="btn-1 ac">Entrar</button>
                            </Link>
                            </div>

                            <div className="display-f ac mt-5">
                                <p className="content-login">não possui conta?</p><Link className="content-login ml-1 link-2" to="/Signup">clique aqui para cadastrar</Link>
                            </div>
                        </div>
                    </div>

                </div>
        )
     }
}

// src/views/public/Login.vue
<template>
    <div>

        <b-container class="bv-example-row mt-7">
            <b-row class="brake-small">

                <b-col>
                    <!-- <img src="../../../public/card-login.png" class="ac img-login"> -->
                    <span class="ac icon-login" v-html="Svgs.helpDelivreyLogo"></span>
                </b-col>


                <b-col>
                    <b-card class="p5 card-style-1 mt-4 mb-6">
                        <h2>Login</h2>

                        <vs-input class="ac mt-4" type="text" placeholder="Email" v-model="email"/>
                        <vs-input class="ac mt-4" type="password" placeholder="Senha" v-model="password"/>

                        <vs-button to="/DashBoard" class="mt-3" type="gradient">Entrar</vs-button>

                        <span class="display-b mt-3">
                            ainda não possui cadastro?
                            <a class="blue-link" @click="goToSignup()">faça o cadastro</a>
                        </span>
                    </b-card>
                </b-col>
            </b-row>
        </b-container>
    </div>
</template>
<script>
import Svgs from '../../assets/svgs/svgSet'

export default {
    data:() => ({
        Svgs:Svgs,

        email:'',
        password:'',
    }),

    methods: {
        goToSignup(){
            this.$router.push('/Signup')
        }
    },
}
</script>
