// skeleton-react-app/src/pages/Signup/index.js
import React from 'react'
import './style.scss'
import { Link } from 'react-router-dom'
import capaImg from '../../assets/capa.png'


export default class Dashboard extends React.Component{
     render(){
        return(
                <div className="container-sides mt-10">

                <div className="container-left ac mt-9">
                    <img className="display-b ac" src={capaImg} alt="delivery"/>
                </div>

                <div className="container-rigth ac">
                    <div className="card card-login">


                            <h1 className="title txt-alg-c mt-3">Cadastrar</h1>

                            <form className="mt-5">
                                <input type="text" className="input-1 mt-2 ac" placeholder="nome"/>
                                <input type="email" className="input-1 mt-4 ac" placeholder="email"/>
                                <input type="password" className="input-1 mt-4 ac" placeholder="senha"/>
                                <input type="password" className="input-1 mt-4 ac" placeholder="Confirme a senha"/>
                            </form>

                            
                            <div className="container-link-login ac mt-5">
                            <Link className="link-1" to="/Dashboard">
                                <button className="btn-1 ac">Cadastrar</button>
                            </Link>
                            </div>

                            <div className="display-f ac mt-5">
                                <p className="content-login">já possui conta?</p><Link className="content-login ml-1 link-2" to="/Login">clique aqui para entrar</Link>
                            </div>
                        </div>
                    </div>

                </div>
        )
     }
}

// src/views/public/Signup.vue
<template>
    <div>

        <b-container class="bv-example-row mt-9">
            <b-row class="brake-small">
                <b-col>
                    <img src="../../../public/card-signup.png" class="ac img-login">
                    <!-- <span class="ac" v-html="Svgs.helpDelivreyLogo"></span> -->
                    <!-- <p>Um app para te ajudar no seu dia dia em casa</p> -->
                </b-col>


                <b-col>
                    <b-card class="p5 card-style-1 mt-4 mb-7">
                        <h2>Cadastro</h2>

                        <div class="centerx">
                            <vs-input class="ac mt-4" type="text" placeholder="Email" v-model="userForm.name"/>
                            <vs-input class="ac mt-4" type="text" placeholder="Email" v-model="userForm.name"/>
                            <vs-input class="ac mt-4" type="number" placeholder="phone" v-model="userForm.phone"/>
                            <vs-input class="ac mt-4" type="text" placeholder="password" v-model="userForm.password"/>
                        </div>

                        <vs-button to="/About" class="mt-3" type="gradient">Cadastrar</vs-button>

                        <span class="display-b mt-3">
                            já possui cadastro?
                            <a class="blue-link" @click="goToLogin()">faça o login</a>
                        </span>
                    </b-card>
                </b-col>
            </b-row>
        </b-container>
    </div>
</template>

<script>
import Svgs from '../../assets/svgs/svgSet'

export default {
    data:() => ({
        Svgs:Svgs,
        userForm:{
            name:'',
            email:'',
            phone:'',
            password:''
        }
    }),

    
    methods: {
        goToLogin(){
            this.$router.push('/Login')
        }
    },
}
</script>
